### PR TITLE
Update NLP sample app and README for HERE SDK 3.6 release

### PR DESCRIPTION
**Pull request by JohnLXiang**

### CODE REVIEW

**Comment by JohnLXiang** [comment]
@sschuberth The Travis build failed for this PR, I think I did what the error message wants, any ideas?Thanks.

**Comment by sschuberth** [comment]
@JohnLXiang Well, we're using a composite build here, and the error message says:

> In the case of composite builds, also make sure the build script classpaths that contain the Android Gradle plugin are identical across the main and included projects.

I'll double-check that.

**Comment by sschuberth** [comment]
@JohnLXiang I've made some fixes to your branch, but additionally @SirBif needs to update the HERE SDK URL in CI to use version 3.6. Please remember that HERE SDK updates still need to be done manually.

**Comment by sschuberth** [comment]
@JohnLXiang, all done, thanks @SirBif for the help.

**Pull request merged**
