### PR TITLE
Add NLP sample app and update README file

### PR DESCRIPTION
**Pull request by JohnLXiang**

### CODE REVIEW

**Comment by JohnLXiang** [comment]
@sschuberth The Travis build failed on Android SDK licensing issue, re-triggering it didn't resolve the problem this time. Could you have someone to look into this? Thanks a lot.

**Comment by sschuberth** [comment]
@JohnLXiang, I've fixed the Android SDK licensing issue in a new commit, but the new example has a compilation error, see

https://travis-ci.org/heremaps/here-android-sdk-examples/builds/287188367#L1649

Is the HERE SDK version required for this already public?

**Comment by JohnLXiang** [comment]
@sschuberth The HERE Android SDK 3.5 that went live on developer.here.com last week should already include these APIs. I just verified it could compile on my local machine. Maybe the location that Travis grabs SDK from hasn't been synced up yet?

**Comment by sschuberth** [comment]
@JohnLXiang, yes, the `HERE_SDK_URL` needs to be updated manually in the Travis CI settings. @SirBif can help with that as I'm on PTO currently.

**Comment by SirBif** [comment]
I updated the SDK and restarted the build

**Comment by sschuberth** [comment]
Thanks @SirBif! Now it seems you need to fix some Lint issues, @JohnLXiang.

**Pull request merged**
