### PR TITLE
Build system improvements

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by SirBif** [comment]
Why didn't you update the JVM settings in all projects but only in some? Is this intentional?

**Comment by sschuberth** [comment]
> Why didn't you update the JVM settings in all projects but only in some? Is this intentional?

My intention was do add the JVM option to all `gradle.properties` files that lack it. Which ones did I miss?

**Comment by SirBif** [comment]
You didn't miss any, looks good. But it was hard to verify with the web UI, now that I checked out the pull request I feel confident ;)

**Pull request merged**
